sbgECom: src/misc/sbgStreamBuffer.h File Reference
sbgStreamBuffer.h File Reference
Used to read/write data from/to a memory buffer stream.
#include "../sbgCommon.h"
#include "sbgSwap.h"
#include <string.h>
Data Structures
struct _StreamBuffer
Typedefs
typedef enum _SbgSBMode SbgSBMode
typedef enum _SbgSBSeekOrigin SbgSBSeekOrigin
typedef struct _StreamBuffer SbgStreamBuffer
Enumerations
enum _SbgSBMode {
SB_MODE_READ,
SB_MODE_WRITE
}
enum _SbgSBSeekOrigin {
SB_SEEK_SET,
SB_SEEK_CUR_INC,
SB_SEEK_CUR_DEC,
SB_SEEK_END
}
Functions
SBG_INLINE SbgErrorCode sbgStreamBufferInitForWrite (SbgStreamBuffer *pHandle, void *pLinkedBuffer, uint32 bufferSize)
SBG_INLINE SbgErrorCode sbgStreamBufferInitForRead (SbgStreamBuffer *pHandle, const void *pLinkedBuffer, uint32 bufferSize)
SBG_INLINE uint32 sbgStreamBufferGetSize (SbgStreamBuffer *pHandle)
SBG_INLINE uint32 sbgStreamBufferGetLength (SbgStreamBuffer *pHandle)
SBG_INLINE uint32 sbgStreamBufferGetSpace (SbgStreamBuffer *pHandle)
SBG_INLINE SbgErrorCode sbgStreamBufferSeek (SbgStreamBuffer *pHandle, uint32 offset, SbgSBSeekOrigin origin)
SBG_INLINE uint32 sbgStreamBufferTell (SbgStreamBuffer *pHandle)
SBG_INLINE void * sbgStreamBufferGetLinkedBuffer (SbgStreamBuffer *pHandle)
SBG_INLINE void * sbgStreamBufferGetCursor (SbgStreamBuffer *pHandle)
SBG_INLINE int8 sbgStreamBufferReadInt8 (SbgStreamBuffer *pHandle)
SBG_INLINE uint8 sbgStreamBufferReadUint8 (SbgStreamBuffer *pHandle)
SBG_INLINE int16 sbgStreamBufferReadInt16 (SbgStreamBuffer *pHandle)
SBG_INLINE uint16 sbgStreamBufferReadUint16 (SbgStreamBuffer *pHandle)
SBG_INLINE int32 sbgStreamBufferReadInt32 (SbgStreamBuffer *pHandle)
SBG_INLINE uint32 sbgStreamBufferReadUint32 (SbgStreamBuffer *pHandle)
SBG_INLINE int64 sbgStreamBufferReadInt64 (SbgStreamBuffer *pHandle)
SBG_INLINE uint64 sbgStreamBufferReadUint64 (SbgStreamBuffer *pHandle)
SBG_INLINE float sbgStreamBufferReadFloat (SbgStreamBuffer *pHandle)
SBG_INLINE double sbgStreamBufferReadDouble (SbgStreamBuffer *pHandle)
SBG_INLINE SbgErrorCode sbgStreamBufferReadBuffer (SbgStreamBuffer *pHandle, void *pBuffer, uint32 numBytesToRead)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt8 (SbgStreamBuffer *pHandle, int8 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint8 (SbgStreamBuffer *pHandle, uint8 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt16 (SbgStreamBuffer *pHandle, int16 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint16 (SbgStreamBuffer *pHandle, uint16 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt32 (SbgStreamBuffer *pHandle, int32 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint32 (SbgStreamBuffer *pHandle, uint32 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt64 (SbgStreamBuffer *pHandle, int64 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint64 (SbgStreamBuffer *pHandle, uint64 value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteFloat (SbgStreamBuffer *pHandle, float value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteDouble (SbgStreamBuffer *pHandle, double value)
SBG_INLINE SbgErrorCode sbgStreamBufferWriteBuffer (SbgStreamBuffer *pHandle, const void *pBuffer, uint32 numBytesToWrite)
Detailed Description
Used to read/write data from/to a memory buffer stream.
Author
SBG Systems (Raphael Siryani)
Date
02 January 2013
Copyright Notice
Copyright (C) 2007-2013, SBG Systems SAS. All rights reserved.
This source code is intended for use only by SBG Systems SAS and those that have explicit written permission to use it from SBG Systems SAS.
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
Typedef Documentation
typedef enum _SbgSBMode SbgSBMode
Stream buffer modes.
typedef enum _SbgSBSeekOrigin SbgSBSeekOrigin
Enum used to define all seek modes
typedef struct _StreamBuffer SbgStreamBuffer
Defines a stream buffer.
Enumeration Type Documentation
enum _SbgSBMode
Stream buffer modes.
Enumerator
SB_MODE_READ
This stream buffer can perform read operations.
SB_MODE_WRITE
This stream buffer can perform write operations.
enum _SbgSBSeekOrigin
Enum used to define all seek modes
Enumerator
SB_SEEK_SET
The offset is referenced to the begining of the stream.
SB_SEEK_CUR_INC
The offset is referenced to the current cursor position and increment the current cursor.
SB_SEEK_CUR_DEC
The offset is referenced to the current cursor position and decrement the current cursor.
SB_SEEK_END
The offset is referenced to the end of the stream.
Function Documentation
SBG_INLINE SbgErrorCode sbgStreamBufferInitForWrite (SbgStreamBuffer * pHandle, void * pLinkedBuffer, uint32 bufferSize)
Initialize a stream buffer for both read and write operations and link it to a buffer.
Parameters
[in] pHandle Handle on an allocated stream buffer.
[in] pLinkedBuffer Pointer on an allocated buffer to link with this stream.
[in] bufferSize Size in bytes of the linked buffer.
Returns
SBG_NO_ERROR if the stream buffer has been initialized successfully.
References _StreamBuffer::bufferSize, _StreamBuffer::modes, _StreamBuffer::pBufferPtr, _StreamBuffer::pCurrentPtr, SB_MODE_WRITE, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferInitForRead (SbgStreamBuffer * pHandle, const void * pLinkedBuffer, uint32 bufferSize)
Initialize a stream buffer for both read and write operations and link it to a buffer.
Parameters
[in] pHandle Handle on an allocated stream buffer.
[in] pLinkedBuffer Pointer on an allocated buffer to link with this stream.
[in] bufferSize Size in bytes of the linked buffer.
Returns
SBG_NO_ERROR if the stream buffer has been initialized successfully.
References _StreamBuffer::bufferSize, _StreamBuffer::modes, _StreamBuffer::pBufferPtr, _StreamBuffer::pCurrentPtr, SB_MODE_READ, and SBG_NO_ERROR.
SBG_INLINE uint32 sbgStreamBufferGetSize (SbgStreamBuffer * pHandle)
Returns the size in bytes of this stream. The size is the linked buffer total size in bytes. For example, for a SbgStreamBuffer linked with a buffer of 256 bytes, this method will always returns 256 even if no data has been written or read.
Parameters
[in] pHandle Valid handle on a stream buffer.
Returns
The allocated size of the linked buffer in bytes.
References _StreamBuffer::bufferSize.
Referenced by sbgStreamBufferGetSpace().
SBG_INLINE uint32 sbgStreamBufferGetLength (SbgStreamBuffer * pHandle)
Returns the length in bytes of this stream. The length is computed using the current cursor position. If no data has been read or written, this method will return 0. If 4 uint32 has been written, it should return 16.
Parameters
[in] pHandle Valid handle on a stream buffer.
Returns
The current cursor position in bytes.
References _StreamBuffer::pBufferPtr, and _StreamBuffer::pCurrentPtr.
Referenced by sbgStreamBufferGetSpace().
SBG_INLINE uint32 sbgStreamBufferGetSpace (SbgStreamBuffer * pHandle)
Returns the available space in this stream. The available space is just the delta between the linked buffer size and the current buffer length (cursor position).
Parameters
[in] pHandle Valid handle on a stream buffer.
Returns
The space available in this stream buffer in bytes.
References sbgStreamBufferGetLength(), and sbgStreamBufferGetSize().
SBG_INLINE SbgErrorCode sbgStreamBufferSeek (SbgStreamBuffer * pHandle, uint32 offset, SbgSBSeekOrigin origin)
Move the current cursor position.
Parameters
[in] pHandle Valid handle on a stream buffer.
[in] offset Offset in bytes to apply (only positive).
[in] origin Origin reference point to apply the offset from.
Returns
SBG_NO_ERROR if the stream current cursor position has been moved.
References _StreamBuffer::bufferSize, _StreamBuffer::pBufferPtr, _StreamBuffer::pCurrentPtr, SB_SEEK_CUR_DEC, SB_SEEK_CUR_INC, SB_SEEK_END, SB_SEEK_SET, SBG_INVALID_PARAMETER, and SBG_NO_ERROR.
SBG_INLINE uint32 sbgStreamBufferTell (SbgStreamBuffer * pHandle)
Returns the current offset in bytes from the beginning of the stream.
Parameters
[in] pHandle Valid handle on a stream buffer.
Returns
Current offset in bytes from the beginning.
References _StreamBuffer::pBufferPtr, and _StreamBuffer::pCurrentPtr.
SBG_INLINE void* sbgStreamBufferGetLinkedBuffer (SbgStreamBuffer * pHandle)
Returns a pointer on the internal buffer.
Parameters
[in] pHandle Valid handle on a stream buffer.
Returns
Pointer on the begining of the internal buffer.
References _StreamBuffer::pBufferPtr.
SBG_INLINE void* sbgStreamBufferGetCursor (SbgStreamBuffer * pHandle)
Returns a pointer on the internal buffer at the current cursor.
Parameters
[in] pHandle Valid handle on a stream buffer.
Returns
Pointer on the current cursor of the internal buffer.
References _StreamBuffer::pCurrentPtr.
SBG_INLINE int8 sbgStreamBufferReadInt8 (SbgStreamBuffer * pHandle)
Read an int8 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References _StreamBuffer::pCurrentPtr.
SBG_INLINE uint8 sbgStreamBufferReadUint8 (SbgStreamBuffer * pHandle)
Read an uint8 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References _StreamBuffer::pCurrentPtr.
SBG_INLINE int16 sbgStreamBufferReadInt16 (SbgStreamBuffer * pHandle)
Read an int16 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References _StreamBuffer::pCurrentPtr.
SBG_INLINE uint16 sbgStreamBufferReadUint16 (SbgStreamBuffer * pHandle)
Read an uint16 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References _StreamBuffer::pCurrentPtr.
SBG_INLINE int32 sbgStreamBufferReadInt32 (SbgStreamBuffer * pHandle)
Read an int32 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References _StreamBuffer::pCurrentPtr.
SBG_INLINE uint32 sbgStreamBufferReadUint32 (SbgStreamBuffer * pHandle)
Read an uint32 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References _StreamBuffer::pCurrentPtr.
Referenced by sbgStreamBufferReadFloat(), sbgStreamBufferReadInt64(), and sbgStreamBufferReadUint64().
SBG_INLINE int64 sbgStreamBufferReadInt64 (SbgStreamBuffer * pHandle)
Read an int64 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References sbgStreamBufferReadUint32().
SBG_INLINE uint64 sbgStreamBufferReadUint64 (SbgStreamBuffer * pHandle)
Read an uint64 from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References sbgStreamBufferReadUint32().
Referenced by sbgStreamBufferReadDouble().
SBG_INLINE float sbgStreamBufferReadFloat (SbgStreamBuffer * pHandle)
Read an float from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References sbgStreamBufferReadUint32().
SBG_INLINE double sbgStreamBufferReadDouble (SbgStreamBuffer * pHandle)
Read an double from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
Returns
The read value or 0 if we have an error.
References sbgStreamBufferReadUint64().
SBG_INLINE SbgErrorCode sbgStreamBufferReadBuffer (SbgStreamBuffer * pHandle, void * pBuffer, uint32 numBytesToRead)
Read a buffer from a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports read operations.
[out] pBuffer Allocated buffer used to hold read data.
[in] numBytesToRead Number of bytes to read from the stream buffer and to store in pBuffer.
Returns
SBG_NO_ERROR if the data has been read.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt8 (SbgStreamBuffer * pHandle, int8 value)
Write an int8 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint8 (SbgStreamBuffer * pHandle, uint8 value)
Write an uint8 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt16 (SbgStreamBuffer * pHandle, int16 value)
Write an int16 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint16 (SbgStreamBuffer * pHandle, uint16 value)
Write an uint16 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt32 (SbgStreamBuffer * pHandle, int32 value)
Write an int32 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint32 (SbgStreamBuffer * pHandle, uint32 value)
Write an uint32 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
Referenced by sbgStreamBufferWriteFloat().
SBG_INLINE SbgErrorCode sbgStreamBufferWriteInt64 (SbgStreamBuffer * pHandle, int64 value)
Write an int64 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
SBG_INLINE SbgErrorCode sbgStreamBufferWriteUint64 (SbgStreamBuffer * pHandle, uint64 value)
Write an uint64 into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.
Referenced by sbgStreamBufferWriteDouble().
SBG_INLINE SbgErrorCode sbgStreamBufferWriteFloat (SbgStreamBuffer * pHandle, float value)
Write an float into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References sbgStreamBufferWriteUint32().
SBG_INLINE SbgErrorCode sbgStreamBufferWriteDouble (SbgStreamBuffer * pHandle, double value)
Write an double into a stream buffer
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[in] value The value to write.
Returns
SBG_NO_ERROR if the value has been successfully written.
References sbgStreamBufferWriteUint64().
SBG_INLINE SbgErrorCode sbgStreamBufferWriteBuffer (SbgStreamBuffer * pHandle, const void * pBuffer, uint32 numBytesToWrite)
Write a buffer to a stream buffer.
Parameters
[in] pHandle Valid stream buffer handle that supports write operations.
[out] pBuffer Buffer to write into the stream buffer.
[in] numBytesToRead Number of bytes to write to the stream buffer.
Returns
SBG_NO_ERROR if the data has been written.
References _StreamBuffer::pCurrentPtr, and SBG_NO_ERROR.