sbgECom: src/misc/sbgSwap.h File Reference
sbgSwap.h File Reference
Set of functions used to swap numbers.
#include "../sbgCommon.h"
Data Structures
union _FloatNint
union _DoubleNint
Typedefs
typedef union _FloatNint FloatNint
typedef union _DoubleNint DoubleNint
Functions
SBG_INLINE uint16 swap16 (uint16 x)
SBG_INLINE uint32 swap32 (uint32 x)
SBG_INLINE uint64 swap64 (uint64 x)
SBG_INLINE float swapFloat (float val)
SBG_INLINE double swapDouble (double val)
Detailed Description
Set of functions used to swap numbers.
Author
SBG Systems (Raphael Siryani)
Date
14 January 2013
Copyright Notice
Copyright (C) 2007-2013, SBG Systems SAS. All rights reserved.
This source code is intended for use only by SBG Systems SAS and those that have explicit written permission to use it from SBG Systems SAS.
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
Typedef Documentation
typedef union _FloatNint FloatNint
Union that allows type punning (access to a floating point number bits)
typedef union _DoubleNint DoubleNint
Union that allows type punning (access to a double number bits)
Function Documentation
SBG_INLINE uint16 swap16 (uint16 x)
Swap a uint16 number.
Parameters
[in] x The uint16 to swap.
Returns
The swapped value.
SBG_INLINE uint32 swap32 (uint32 x)
Swap a uint32 number.
Parameters
[in] x The uint32 to swap.
Returns
The swapped value.
Referenced by swap64(), and swapFloat().
SBG_INLINE uint64 swap64 (uint64 x)
Swap a uint64 number.
Parameters
[in] x The uint64 to swap.
Returns
The swapped value.
References swap32().
Referenced by swapDouble().
SBG_INLINE float swapFloat (float val)
Swap a float number.
Parameters
[in] val The float to swap.
Returns
The swapped value.
References swap32().
SBG_INLINE double swapDouble (double val)
Swap a double number.
Parameters
[in] val The double to swap.
Returns
The swapped value.
References swap64().